### ISSUE TITLE
services API needs to be fixed and more dynamic

### ISSUE THREAD

**Issue by mchigit** [ryanprice/Cryptoz.cards-Dapp#16]
https://cryptoz.cards/data/2 ( served from cryptoz-cards-server scripts)
The services API needs to be fixed and more dynamic

**Comment by ryanprice** [comment]
node script outside of this repo that watches for events, updates the DB

contract.on("LogCardCreated", (owner, tokenId, editionNum, cardTypeID, rarity, cxzp) => {DO STUFF HERE}

Also a getPastCardsCreated scripts that will reset all the token data.
