### ISSUE TITLE
Buy and Get buttons in Shop should be disabled if wallet has purchased/claimed already

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/Cryptoz.cards-Dapp#18]
The contracts track all purchases/gets from the shop to every wallet. Therefore the buy/get button should be disabled upon purchase or the card detecting the item is already purchased

**Comment by ryanprice** [comment]
test

**Comment by jjjhill** [comment]
We should also make it clear to the user that they can only buy/get 1 of each

**Comment by mchigit** [comment]
> We should also make it clear to the user that they can only buy/get 1 of each

Yep, that will be part of my work. I was thinking of changing the button text when disabled and maybe have a tooltip or something
