### ISSUE TITLE
Provide a DataTable view in the Crypt eventually

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/Cryptoz.cards-Dapp#24]
The Crypt displays full cards which is nice.. but if a player has 100s of cards, it would be nice to have an alternative condensed table that is just a data view, something like 

- Card name
- mini img thumbnail
- Card Level
- Edition Num.
- UnlockCZXP
- SacrificeCZXP
- SacrificeButton
- GiftButton

**Comment by jjjhill** [comment]
https://github.com/ryanprice/Cryptoz.cards-Dapp/pull/34
