### ISSUE TITLE
Clicking from event feed stacks 2 collections

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/Cryptoz.cards-Dapp#253]
When sitting on the https://movr.zoombies.world/my-zoombies-nfts page and then clicking an event to view another's crypt i.e: 0x5be.., 
the other crypt nfts are stacked on my nfts.

![image](https://user-images.githubusercontent.com/180252/157540064-028a4f77-a8c3-4f96-9f91-8ea249fb70b1.png)

**Comment by mchigit** [comment]
hmm I couldn't really reproduce this 😅 I clicked on another crypt and was able to reload the other person's nfts. tested on both moonriver and moonbase alpha @ryanprice

**Comment by ryanprice** [comment]
I think if you sit and watch, the newly minted NFTs will appear on top. I'll try again and get an exact set of steps to reproduce this
