### ISSUE TITLE
Network name isnt always correct in footer

### ISSUE THREAD

**Issue by jjjhill** [ryanprice/Cryptoz.cards-Dapp#28]
Web3 v0.20.7 doesn't have a getChainId function so we can't get it if Metamask wallet is already connected to the site on mount. The solution for this is find another way to get chainId from window.ethereum or web3 0.20.7, or upgrade to web3 1.x

**Comment by ryanprice** [comment]
hmm ok, will look into this. web3 1.x is breaking changes.. it would be good if we want to go through the changes. AND/OR  we go https://docs.ethers.io/v5/  which is what I am using now for the log scraper after failing to figure it out with web3js 1.x

**Comment by ryanprice** [comment]
I have added some network change detection code in the #65 request. It may not be 100%. but it's a start
