### ISSUE TITLE
UX Suggestions 

### ISSUE THREAD

**Issue by nlambb** [ryanprice/Cryptoz.cards-Dapp#30]
Shop:
- Slight update to description:
“The Shop is a place to mint limited edition Cryptoz cards. Some cards are free, some have a cost. 
To buy a limited edition card, or to claim one for free, you will need the minimum balance of CZXP tokens indicated on the         card. After buying or claiming a card, its CZXP value will be added to your balance.
You may also buy and open a booster card, which will randomly mint an unlimited edition card"

- Might look better to retain the colour scheme and bezel colour on the back side of a card. Always defaults to blue.
- The number in the green circle on the bottom right of a card is not centered. And since this number is aligned with the number in the bottom left/middle of the card (the ID?), both of them should be raised a bit to be centered (unless it's a design choice to have the ID number hug the bottom border?)
- The ‘Buy Booster Credits @ 0.002E’ and ‘Buy Card 0.002E’ buttons seem inconsistent, either they should both have the @ symbol or neither should.
- Long names e.g. “Cool Flame Japanese Cherry Tree” are wider than card
- Port spinner to “buy card” buttons in shop. Seems like nothing is happening for a few seconds
- Would be satisfying to have some kind of ‘!’ or other notification beside the Crypt tab when you mint a new card
- It might look good having the CZXP logo beside the “Your CZXP Balance” (on second thought, is the circle with the blue skull the CZXP ‘logo’? This looks to be the case in the Markets tab and the Help tab, but this logo also appears on the bottom left of each card beside the ID (?) which has nothing to do with CZXP, so the ID number might be misleading)
- “Your Boosters : ” vs “Your Cryptoz: ” vs “Your CZXP Balance :” change these to maintain consistency with the colon spacing
- "Get Card #" button on free cards: not clear what this number represents, and following the 'buy card' button's convention, it would seem to be a cost or a CZXP amount.
- Could display a legend for the card tier list, and an explanation for what the number beside the tier ("Mystical 1") represents

Crypt: 
“This is where all your Cryptoz cards can be accessed. From here you can sort your cards, sacrifice them for additional CZXP, or transfer them to another wallet. Sacrificing is permanent, not only in your wallet but across the entire Cryptoz universe - that unique item will be gone forever. 

- There's no 'search' function yet, even though this was in the original description
- If you have a lot of cards in the Crypt, it can be hard to see which card just came out of a booster or the shop. Could be nice to have a “New” sticker or something that disappears when the page is refreshed / some time after the card has been hovered over
- When opening a booster card, the ‘CZXP wager amount’ popup seems clunky. What does it mean for the Minimum to be “0 Or 2,000,000,000”? And it would look cleaner if the “Maximum = 1,649,….” was on the next line

Help:
- It would look better if the question marks weren’t spaced from the questions like they are here
- CZXP logo beside CZXP: spacing looks weird, also the CZXP logo would look more seamless if it were smaller
- Some questions are unanswered, I can help write up responses

Markets: 
- OpenSea box cuts into Rare Bits box, at least when it’s hovered over
- “erc-721 tokens are supported on the following auction marketplaces:” add a colon
- “erc-20 tokens are supported on the following token exchanges:” add colon
- CryptoZ eXPERience (CZXP)  - the logo would look less out of place if it was made smaller

- “Buy, sell, and discover unique crypto assets.” – add a period to this
- “Decentralized Ethereum Asset Exchange.” – add period

**Comment by ryanprice** [comment]
> Shop:
> 
> * Might look better to retain the colour scheme and bezel colour on the back side of a card. Always defaults to blue.

I hear ya, its part of the card design, like if you bought a deck. not sure we would change this just yet ? 

> * The ‘Buy Booster Credits @ 0.002E’ and ‘Buy Card 0.002E’ buttons seem inconsistent, either they should both have the @ symbol or neither should.

The intent here is to communicate that you can buy more than 1 booster @ a rate of 0.002E x # of credits.    The Buy card button value will vary depending on the cost of the card. and its a static amount  Buy 1 card for 0.002E. but if that's confusing, may be worth a change

> * Long names e.g. “Cool Flame Japanese Cherry Tree” are wider than card

So far I have been resolving these by shortening the name in the DB, instead of altering font size dynamically or card layout

> * It might look good having the CZXP logo beside the “Your CZXP Balance” (on second thought, is the circle with the blue skull the CZXP ‘logo’? This looks to be the case in the Markets tab and the Help tab, but this logo also appears on the bottom left of each card beside the ID (?) which has nothing to do with CZXP, so the ID number might be misleading)

the czxp logo is being used to respresent the token itself.  but ya it could be a bit confusing to see it being used in other cases.
On every card, the number along the bottom between the logo and the Green circle level. is the required czxp to unlock a card.
I am going to have our designed create a "Card Legend" which explains what all the data is on the card itself, to put in the FAQ

> * “Your Boosters : ” vs “Your Cryptoz: ” vs “Your CZXP Balance :” change these to maintain consistency with the colon spacing
> * "Get Card #" button on free cards: not clear what this number represents, and following the 'buy card' button's convention, it would seem to be a cost or a CZXP amount.

Agreed, will update

> * Could display a legend for the card tier list, and an explanation for what the number beside the tier ("Mystical 1") represents
Yes, Card Legend coming
> 
> Crypt:
> * There's no 'search' function yet, even though this was in the original description

Agreed, we can add as an enhancement

> * If you have a lot of cards in the Crypt, it can be hard to see which card just came out of a booster or the shop. Could be nice to have a “New” sticker or something that disappears when the page is refreshed / some time after the card has been hovered over

Yes, definitely a nice to have, or popup a modal to focus it, we could add as an enhancement

> * When opening a booster card, the ‘CZXP wager amount’ popup seems clunky. What does it mean for the Minimum to be “0 Or 2,000,000,000”? And it would look cleaner if the “Maximum = 1,649,….” was on the next line

This is a weird requirement in the contracts for a feature we want to highlight. its like betting to increase your odds of pulling a better card. but the min. you have to put in is 2 bil tokens or higher to start the increase of odds .. I may need to come up with some visual to explain this better

> 
> Help:
> 
> * It would look better if the question marks weren’t spaced from the questions like they are here
> * CZXP logo beside CZXP: spacing looks weird, also the CZXP logo would look more seamless if it were smaller
> * Some questions are unanswered, I can help write up responses

Sounds good, will do some updates
Yes !
> 
> Markets:
> 
> * OpenSea box cuts into Rare Bits box, at least when it’s hovered over

Rarebits is removed in an upcoming push

> * “erc-721 tokens are supported on the following auction marketplaces:” add a colon
> * “erc-20 tokens are supported on the following token exchanges:” add colon
> * CryptoZ eXPERience (CZXP)  - the logo would look less out of place if it was made smaller
> * “Buy, sell, and discover unique crypto assets.” – add a period to this
> * “Decentralized Ethereum Asset Exchange.” – add period

Sounds good, updates coming

Thanks for all the feedback

**Comment by ryanprice** [comment]
Size has evolved.. some of this got implemented. Thanks Nick
