### ISSUE TITLE
Routinely pulling exceedingly rare cards from boosters

### ISSUE THREAD

**Issue by nlambb** [ryanprice/Cryptoz.cards-Dapp#38]
I've pulled 6 purple cards in the span of 15-20 boosters, which is (or should be) essentially impossible. All of them had wager 0.
There might be something wrong with the booster algorithm.
Also I'm sure this is repeatable; try opening like 5 boosters and see what happens.

**Comment by ryanprice** [comment]
This should be resolved, Open a  bunch of boosters to verify

**Comment by nlambb** [comment]
Looks good now!
