### ISSUE TITLE
'Get Card' and 'Buy Card' throwing Metamask "Transaction Error"

### ISSUE THREAD

**Issue by nlambb** [ryanprice/Cryptoz.cards-Dapp#39]
SOME of the buy/get buttons in the shop don't allow the transaction to be completed, even when the CZXP and Eth requirements are met. In the Metamask transaction screen, it shows: ALERT: Transaction Error. Exception thrown in contract code. Can accept the transaction anyway but an alert eventually shows that the "Transaction Failed" and the minted card does not show up in crypt. This happens for some buttons and not others, and I'm trying to find out what the conditions are for this to happen. 
Let me know if the buy/get transactions always work for you guys.

**Comment by ryanprice** [comment]
Resolved along the way somewhere
