### ISSUE TITLE
Wagering CZXP does not detract any CZXP from account balance

### ISSUE THREAD

**Issue by nlambb** [ryanprice/Cryptoz.cards-Dapp#44]
When opening a booster, anything I successfully wager will not be removed from my balance. I can wager my entire balance and nothing happens.

**Comment by ryanprice** [comment]
You can check the balance in the contract here https://rinkeby.etherscan.io/token/0x6ac8567d2c57589166c1fa5e2214d17e6c896ec9#balances

**Comment by ryanprice** [comment]
completed
