### ISSUE TITLE
Able to wager any amount of CZXP greater than 2,520,000 

### ISSUE THREAD

**Issue by nlambb** [ryanprice/Cryptoz.cards-Dapp#45]
Updating this issue because I misinterpreted the minimum/maximum wager system.

I am able to make a wager of 2,520,000 or higher even though the minimum wager amount is 2 billion.

**Comment by jjjhill** [comment]
@ryanprice what is desired behavior here? we need to update the frontend with validations for this

**Comment by ryanprice** [comment]
Fixed in pr #52
