### ISSUE TITLE
After logging in to metamask, "Your CZXP Balance" shows 0 until a CZXP interaction has been made

### ISSUE THREAD

**Issue by nlambb** [ryanprice/Cryptoz.cards-Dapp#46]
I've noticed this for a while; every time I start the dev server, go into the app and connect to metamask, the CZXP balance shows 0 until I do something. As soon as I do some interaction with CZXP (sacrifice, buy a card, etc), it immediately loads my previous amount. This isn't simply a display issue, the shop also sees my CZXP balance as 0, and doesn't unlock buttons for cards which require any amount of CZXP. But once I (i.e.) sacrifice a card, my balance loads, and I can use the shop properly. 
Also, even after I do some interaction and my balance shows up, if I close the browser, open a new window and go back to the site, it sees my balance as 0 all over again.

**Comment by ryanprice** [comment]
I think this is resolved now. Please confirm @nlambb

**Comment by mchigit** [comment]
This is working for me now
