### ISSUE TITLE
buy booster credit modal should respect network

### ISSUE THREAD

**Issue by mchigit** [ryanprice/Cryptoz.cards-Dapp#71]
When I'm on BSC, and try to buy booster credits, the button says `Buy Booster at 0.002 BNB`:

![image](https://user-images.githubusercontent.com/19379512/111075294-bda00b80-84bd-11eb-8df2-117303d484bb.png)

But the modal is not in BNB:

![image](https://user-images.githubusercontent.com/19379512/111075297-c7297380-84bd-11eb-9dc7-dc8034f88503.png)

**Comment by ryanprice** [comment]
Code is split, so we won't use this
