### ISSUE TITLE
Test and ensure mobile Trust Wallet works

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/Cryptoz.cards-Dapp#72]
Mobile users #1 request is to use Trust Wallet

**Comment by Empty138** [comment]
I use trust wallet in my mobile and i notice i don't see any item in shopping.
![Screenshot_2021-03-22-01-39-18-558_com wallet crypto trustapp](https://user-images.githubusercontent.com/81138269/111942550-3d2b6d00-8ab2-11eb-8f1d-bac8b187abff.jpg)

**Comment by Empty138** [comment]
Thx very much now my issue is solved.
