### ISSUE TITLE
my NFT crypt doesn't refresh after a sacrifice confirmation

### ISSUE THREAD

**Issue by ryanprice** [ryanprice/Cryptoz.cards-Dapp#81]
It may be a fluke, but I noticed this.
Can test on latest bsc pull

**Comment by mchigit** [comment]
Oh yikes this might be related to the disabling re-loading cards PR I merged. I will take a look at this tonight

**Comment by ryanprice** [comment]
Gifting from the Crypt is working correctly. appears only to be with sacrifice

**Comment by ryanprice** [comment]
Confirmed works correctly
