### ISSUE TITLE
Enter czxp wager lower than x fails

### ISSUE THREAD

**Issue by mchigit** [ryanprice/Cryptoz.cards-Dapp#9]
Repro:
- Try to enter CZXP wager of lower than x fails at database level
- No error handling on FE

Suggestion:
- Put the contract address of CZXP in a more upfront area so users can add their tokens to metamask

![image](https://user-images.githubusercontent.com/19379512/95790514-81b60f80-0cad-11eb-989f-d433a2bcaac4.png)
![image](https://user-images.githubusercontent.com/19379512/95790517-84b10000-0cad-11eb-932e-012f2b3151d6.png)

**Comment by ryanprice** [comment]
You have to wager either 0 OR between 1 bil and 1.6 quadrillion lol.  A little confusing for sure.

**Comment by ryanprice** [comment]
we could validate the value before enabling submit, with a tooltip telling them to increase the wager but also verify they even have enough czxp and then allow the button to enable
